language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: I1kXbL/7o2WhZn+pH2u6qCFHKqtxrSslUgg5I2a6I4Wv/Bf1puxZRpxs/ZAZ61QO8ubwxXjVsqKGpm0NnSFd6P/nCee1Fdg+Ym03kPgfKFMwLkRc+Cm1RHOvbXN5lf/VMDfqNVQ9P5ZLCpDpttd5giszS+ZXzldFrLk4zTH/cjX5Khu57w5oION9lt2HrSQr3lvHbJ4WWk3cdIFUXbmYNmdJP+st4GMaLDKNfl+IgXQ3WyDLW/R6KBgm0LEmpvrl7erqCZAr6xv4cT3QK9+xAnA44ZfT9d7VZmtW/bnL24Al0hgoUATh5N01Dvc6NlUMZvY+1cDgL6XbEOH65Yn0zPq2uRea+J38/TzJ0Os2MW57Vtmw6jF0BPCtBCYwnVnx0hx7nYfP0oB8MpRc2cy2o3kkVj1a/F+np23gTatebxK0ot3Hnz6FK232FD6CusDkzvl2Xwzfq0Rffb9U/ff5AfysnzSzp70kecUtgdmOhQi4nqIpbBmWIS5mmk1kpw5HJGHZey6paiDT2l9ShAcHxdOOC9LRBxh2NSo2hs+Ry7gIKDZBydm4XSFS6qJOKsNZ7Bry4B/c0NXPDFgWYc5nuXV4u4BNKjrFYVeT0UF7MynP0HA1n3hgftfyOZLLhJF9pnra+SFdtlGLL5MnUu0Q163QoAHePFI1Kr0Yj+XKDOY=
